jobs:
  build-test:
    runs-on: ubuntu-latest          # host runner 22.04+
    container:
      image: osrf/ros:foxy-desktop  # <-- changed
      options: --user 0             # keep if you need apt install

    steps:
      - uses: actions/checkout@v4

      - name: Install colcon & Gazebo
        run: |
          apt-get update
          apt-get install -y python3-colcon-common-extensions \
                             python3-vcstool \
                             ros-foxy-gazebo-ros-pkgs
          gazebo --version
      # … rest of your workflow …
