name: CI – ROS 2 Foxy & Gazebo 11 (container)

on: [push, pull_request]

env:
  ROS_DISTRO: foxy          # single place to change if you ever move up

jobs:
  build-test:
    runs-on: ubuntu-latest   # host runner (22.04 as of 2025-05)
    container:
      # Official Docker Hub image built on Ubuntu 20.04 with ROS 2 already in /opt/ros
      image: osrf/ros:foxy-desktop
      # run as root so apt can install extra packages
      options: --user 0

    steps:
      # 1  Fetch your repository
      - uses: actions/checkout@v4

      # 2  Install any extras the base image doesn’t bring
      - name: Install colcon, Gazebo 11, rosdep
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y --no-install-recommends \
              python3-colcon-common-extensions python3-vcstool \
              python3-rosdep ros-${ROS_DISTRO}-gazebo-ros-pkgs
          rosdep init || true
          rosdep update

      # # 4  Build the workspace
      - name: Build project
        id: build
        run: |
          cd /home/ros2_ws/
          . /opt/ros/foxy/setup.sh
          colcon build --packages-up-to gazebo_ros2_control_demos
      - name: Run tests
        id: test
        run: |
          cd /home/ros2_ws/
          . /opt/ros/foxy/setup.sh
          colcon test --event-handlers console_direct+ --packages-select gazebo_ros2_control gazebo_ros2_control_demos
