jobs:
  build-test:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:foxy-desktop
      options: --user 0

    steps:
    - uses: actions/checkout@v4

    - name: Install colcon, Gazebo 11, rosdep
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y --no-install-recommends \
            python3-colcon-common-extensions python3-vcstool \
            python3-rosdep ros-${ROS_DISTRO}-gazebo-ros-pkgs
        gzserver --version  # safe in CI

        rosdep init || true
        rosdep update

    - name: rosdep install
      run: |
        rosdep install --from-paths src --ignore-src -r -y

    - name: colcon build
      run: |
        source /opt/ros/${ROS_DISTRO}/setup.bash
        colcon build --event-handlers console_cohesion+

    - name: colcon test
      run: |
        source install/setup.bash
        colcon test --event-handlers console_cohesion+

    - name: Test results
      run: |
        source install/setup.bash
        colcon test-result --verbose
