name: CI – ROS 2 Foxy & Gazebo 11 (container)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:foxy-desktop
    steps:
      - uses: actions/checkout@v4

      - name: Install extra apt packages
        run: |
          rm /etc/apt/sources.list.d/ros2-latest.list
          rm /usr/share/keyrings/ros2-latest-archive-keyring.gpg
          apt update && apt install -y curl ca-certificates
          export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') ;\
              curl -L -s -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb" \
              && apt-get update \
              && apt-get install /tmp/ros2-apt-source.deb \
              && rm -f /tmp/ros2-apt-source.deb
          apt-get update -qq
          apt-get install -y --no-install-recommends \
            python3-colcon-ros \
            ros-foxy-ament-lint

      - name: Copy sources into workspace 
        run: |
          mkdir -p /home/ros2_ws/src
          cp -r $GITHUB_WORKSPACE/. /home/ros2_ws/src/

      - name: colcon build
        working-directory: /home/ros2_ws
        run: |
          . /opt/ros/foxy/setup.sh
          colcon build --symlink-install --packages-up-to argus_bot

      - name: colcon test
        working-directory: /home/ros2_ws
        run: |
          . install/setup.sh
          colcon test --event-handlers console_direct+ \
                       --packages-select argus_bot
          colcon test-result
