name: CI – ROS 2 Foxy & Gazebo 11 (container)

on: [push, pull_request]

env:
  ROS_DISTRO: foxy          # single place to change if you ever move up

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:foxy-desktop
    steps:
    - uses: actions/checkout@v4
    - name: Setup colcon workspace
      id: configure
      run: |
        cd ..
        mkdir -p /home/ros2_ws/src
        cp -r argus_bot /home/ros2_ws/src/
        apt-get update && apt-get upgrade -q -y
        apt-get update && apt-get install -q -y --no-install-recommends \
          dirmngr \
          gnupg2 \
          lsb-release \
          python3-colcon-ros
        cd /home/ros2_ws/src/
        rosdep update
        rosdep install --from-paths ./ -i -y --rosdistro foxy \
          --ignore-src
    - name: Build project
      id: build
      run: |
        cd /home/ros2_ws/
        . /opt/ros/foxy/setup.sh
        colcon build --packages-up-to argus_bot_demos
    - name: Run tests
      id: test
      run: |
        cd /home/ros2_ws/
        . /opt/ros/foxy/setup.sh
        colcon test --event-handlers console_direct+ --packages-select argus_bot argus_bot_demos
        colcon test-result