name: CI – ROS 2 Foxy & Gazebo 11 (container)

on: [push, pull_request]

env:
  ROS_DISTRO: foxy          # single place to change if you ever move up

jobs:
  build-test:
    runs-on: ubuntu-latest   # host runner (22.04 as of 2025-05)
    container:
      # Official Docker Hub image built on Ubuntu 20.04 with ROS 2 already in /opt/ros
      image: osrf/ros:foxy-desktop
      # run as root so apt can install extra packages
      options: --user 0

    steps:
      # 1  Fetch your repository
      - uses: actions/checkout@v4

      # 2  Install any extras the base image doesn’t bring
      - name: Install colcon, Gazebo 11, rosdep
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y --no-install-recommends \
              python3-colcon-common-extensions python3-vcstool \
              python3-rosdep ros-${ROS_DISTRO}-gazebo-ros-pkgs
          gzserver --version        
          rosdep init || true
          rosdep update


      # 3  Pull third-party dependencies declared in package.xml files
      - name: rosdep install
        run: |
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      # 4  Build the workspace
      - name: colcon build
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          colcon build --event-handlers console_cohesion+

      # 5  Run your CTest / ament tests (if present)
      - name: colcon test
        run: |
          source install/setup.bash
          colcon test --event-handlers console_cohesion+

      # 6  Fail the job if any test failed
      - name: colcon test-result
        run: |
          source install/setup.bash
          colcon test-result --verbose
